--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Daggal/Desktop/Cortex-M0/verilog/prj/al_ip/PLL.vhd
 -- Date	:	2024 05 09
 -- TD version	:	5.6.59063
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:             50.000MHz
--	Clock multiplication factor: 2
--	Clock division factor:       1
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C0        	| 100.000000MHZ	| 0  DEG     
--		C1        	| 25.000000 MHZ	| 0  DEG     
--		C2        	| 25.000000 MHZ	| 90 DEG     
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY eagle_macro;
USE eagle_macro.EAGLE_COMPONENTS.ALL;

ENTITY PLL IS
  PORT (
    refclk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    stdby : IN STD_LOGIC;
    extlock : OUT STD_LOGIC;
    clk0_out : OUT STD_LOGIC;
    clk1_out : OUT STD_LOGIC;
    clk2_out : OUT STD_LOGIC 
  );
END PLL;

ARCHITECTURE rtl OF PLL IS
  SIGNAL clk0_buf :  STD_LOGIC;
  SIGNAL fbk_wire :  STD_LOGIC;
  SIGNAL clkc_wire :  STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
  bufg_feedback : EG_LOGIC_BUFG
  PORT MAP (
    i => clk0_buf,
    o => fbk_wire 
  );

  pll_inst : EG_PHY_PLL
  GENERIC MAP (
    DPHASE_SOURCE => "DISABLE",
    DYNCFG => "DISABLE",
    FIN => "50.000",
    FEEDBK_MODE => "NORMAL",
    FEEDBK_PATH => "CLKC0_EXT",
    STDBY_ENABLE => "ENABLE",
    PLLRST_ENA => "ENABLE",
    SYNC_ENABLE => "DISABLE",
    DERIVE_PLL_CLOCKS => "DISABLE",
    GEN_BASIC_CLOCK => "DISABLE",
    GMC_GAIN => 4,
    ICP_CURRENT => 13,
    KVCO => 4,
    LPF_CAPACITOR => 1,
    LPF_RESISTOR => 4,
    REFCLK_DIV => 1,
    FBCLK_DIV => 2,
    CLKC0_ENABLE => "ENABLE",
    CLKC0_DIV => 10,
    CLKC0_CPHASE => 9,
    CLKC0_FPHASE => 0,
    CLKC1_ENABLE => "ENABLE",
    CLKC1_DIV => 40,
    CLKC1_CPHASE => 39,
    CLKC1_FPHASE => 0,
    CLKC2_ENABLE => "ENABLE",
    CLKC2_DIV => 40,
    CLKC2_CPHASE => 9,
    CLKC2_FPHASE => 0 
  )
  PORT MAP (
    refclk => refclk,
    reset => reset,
    stdby => stdby,
    extlock => extlock,
    load_reg => '0',
    psclk => '0',
    psdown => '0',
    psstep => '0',
    psclksel => b"000",
    dclk => '0',
    dcs => '0',
    dwe => '0',
    di => b"00000000",
    daddr => b"000000",
    fbclk => fbk_wire,
    clkc => clkc_wire 
  );

  clk0_out <= fbk_wire;
  clk2_out <= clkc_wire(2);
  clk1_out <= clkc_wire(1);
  clk0_buf <= clkc_wire(0);

END rtl;

