--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/Daggal/Desktop/Cortex-M0/verilog/prj/al_ip/SDRAM.vhd
 -- Date	:	2024 05 13
 -- TD version	:	5.6.59063
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
ENTITY SDRAM IS
PORT (
	clk		: IN STD_LOGIC ;
	ras_n		: IN STD_LOGIC ;
	cas_n		: IN STD_LOGIC ;
	we_n		: IN STD_LOGIC ;
	cke		: IN STD_LOGIC
	);
END SDRAM;

ARCHITECTURE struct OF SDRAM IS

	BEGIN
		PORT MAP (
			clk	=> clk,
			addr	=> addr,
			ba	=> ba,
			dq	=> dq,
			cke	=> cke
		);

END struct;
